//! `ciris-registry-core` — the cohabit-target library for CIRISAgent.
//!
//! Phase 4 of CIRISRegistry#33: this crate splits the federation-conformance
//! surface (audit, attestations, federation client, signing, build verification,
//! crypto wiring, edge_transport, CEG §10.1 read-side helpers) out of the
//! Registry binary so CIRISAgent can pull it as a workspace dep alongside
//! `ciris-lens-core` and `ciris-node-core` post-fold.
//!
//! The Registry binary (`ciris-registry`) lives in the sibling crate at
//! `../ciris-registry`; it depends on this lib for all federation-substrate
//! interaction. The bin contributes the gRPC/HTTP server entrypoint + the
//! Stripe billing + public installer endpoint glue.
//!
//! ## Modules
//!
//! - [`crypto`] — `HybridCrypto` (Ed25519 + ML-DSA-65) + `PersistPqcAdapter`
//!   for `ciris_persist::LocalSigner` interop
//! - [`federation`] — `FederationDirectory` trait + NoOp + PersistFederationClient
//! - [`edge_transport`] — CEG 0.2 §10.1 read-side helpers (TTL, SHA verify,
//!   ContentMiss feedback, three-layer composition)
//! - [`build_manifest`] — vendored `BuildManifest` shape for inbound POST
//!   validation
//! - [`db`] — Registry's own persistence layer (postgres via sqlx)
//! - [`services`] — gRPC service implementations
//! - [`api`] — HTTP gateway handlers
//! - [`middleware`] — Tower middleware (auth, metrics, tracing)
//! - [`config`], [`error`], [`validation`], [`capabilities`] — supporting
//!   modules
//! - [`play_integrity`], [`app_attest`], [`auth`], [`rate_limiter`] —
//!   bin-side functionality (kept here in v1.4.0 for the minimal-blast-radius
//!   workspace split; may relocate to the bin crate in a future minor)
//!
//! ## Phase 4 minimal-blast-radius approach
//!
//! v1.4.0 ships the workspace shape with the source tree wholesale-moved
//! to this lib crate; `main.rs` is the thin shim in the sibling bin crate.
//! The lib surface is therefore broader than CIRISAgent strictly needs
//! (it includes gRPC/HTTP server modules CIRISAgent won't link against).
//! That's intentional: structural split first, content split later.
//!
//! A future minor will relocate bin-only modules (`api`, `services`,
//! `middleware`, `rate_limiter`, `play_integrity`, `app_attest`) to the
//! bin crate, keeping only the cohabit-target surface in the lib.

pub mod api;
pub mod app_attest;
// Note: `auth` lives under `middleware::auth` (the JWT validator); no
// top-level auth module exists.
pub mod build_manifest;
pub mod capabilities;
pub mod config;
pub mod crypto;
pub mod db;
pub mod edge_transport;
pub mod error;
pub mod federation;
pub mod middleware;
pub mod play_integrity;
pub mod rate_limiter;
pub mod services;
pub mod validation;

/// Generated protobuf bindings under the `ciris.registry.v1` package.
///
/// Generated by [`build.rs`](../build.rs) via `tonic-build` from
/// `protocol/ciris_registry.proto`. The `FILE_DESCRIPTOR_SET` is used
/// by `tonic-reflection` for the gRPC reflection service.
pub mod proto {
    tonic::include_proto!("ciris.registry.v1");
    pub const FILE_DESCRIPTOR_SET: &[u8] =
        tonic::include_file_descriptor_set!("ciris_registry_descriptor");
}
